title:            Davide Pelosi
description:      Big Data, Machine Learning, Integration, Messaging, Microservices, Cloud, Internet of Things, Blockchain

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/1_Primary_logo_on_transparent_73x37.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://davidepelosi.github.io/blog

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
#menu:
#  - title: 'Home'
#    url: '/'
#  - title: 'Posts'
#    url: '/'
#  - title: 'Tags'
#    url: '/tags'
#  - title: 'Categories'
#    url: '/categories'
#    type: 'categories'

# Owner/author information
owner:
  name:           Davide Pelosi
  site:           http://davidepelosi.eu
  avatar:         images/avatar.jpg
  bio:            "Your bio goes here. It shouldn't be super long but a good two sentences or two should suffice."
  email:          davide.pelosi@dpstudio.eu
  # Twitter nick for use in Twitter cards and follow button.
  twitter: d5pelosi # if no twitter in this config, the twitter follow button will be removed
  # Linkedin nick for use in Linkedin cards and follow button.
  linkedin: davide-pelosi # if no linkedin in this config, the linkedin button will be removed
  # GitHub nick for use in follow button in author block.
  github: davidepelosi

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/davidepelosi"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/davide-pelosi/"
  
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Rome
locale:      it_IT
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
